version: '3.8'

services:
  app:
    build: .
    image: my_python_app
    container_name: my_python_app_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - NAME=World
    restart: unless-stopped
